"""empty message

Revision ID: 46dd8001b89f
Revises: 5a29992a50fd
Create Date: 2024-08-04 17:03:57.951934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46dd8001b89f'
down_revision = '5a29992a50fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
