"""empty message

Revision ID: 5a29992a50fd
Revises: f4705a04e870
Create Date: 2024-08-04 17:01:02.614243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a29992a50fd'
down_revision = 'f4705a04e870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_word',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20), nullable=False),
    sa.Column('chapter', mysql.TEXT(collation='utf8mb3_unicode_ci'), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
