"""empty message

Revision ID: 942010dbe981
Revises: 46dd8001b89f
Create Date: 2024-08-08 15:29:06.254314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942010dbe981'
down_revision = '46dd8001b89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['question'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
