"""empty message

Revision ID: f4705a04e870
Revises: 
Create Date: 2024-07-30 16:10:21.904099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4705a04e870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_word', schema=None) as batch_op:
        batch_op.alter_column('chapter',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_word', schema=None) as batch_op:
        batch_op.alter_column('chapter',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
